### ISSUE TITLE
Critical Bug: Remote Sessions Fail

### ISSUE THREAD

**Issue by markekraus** [PowerShell/WindowsCompatibility#23]
I was writing up some quick start guides and when I went to validate how remote modules worked I discovered the remoting scenario is broken.
Repro:

```powershell
$Credential = Get-Credential
Initialize-WinSession -ComputerName REMOTECOMPUTER -Credential $Credential
Invoke-WinCommand -ScriptBlock { $env:COMPUTERNAME }
```

Expected result:

```none
REMOTECOMPUTER
```

actual result:

```none
LOCALCOMPUTER
```

It looks like commands call `Initialize-WinSession` and if `-ComputerName` and `-ConfigurationName` are not passed to the outer command by the user, The defaults are then used, which initializes or returns the local computer session.

We should adjust the logic in `Initialize-WinSession` to not clobber the exiting remote session with a local session when the module commands are called without the additional paramters, or Initialize-WinSession should update the `$script:DefaultComputerName` and `$script:DefaultConfigurationName` when it initializes a new session.

**Comment by BrucePay** [comment]
This has been fixed by the associated PR.
