### ISSUE TITLE
Merge with PowerShellGet

### ISSUE THREAD

**Issue by Ayanmullick** [PowerShell/WindowsCompatibility#39]
If this was merged with the 'PowerShellGet'  module one could seamlessly import\install "existing Windows PowerShell scripts and modules" in PowerShell Core

**Comment by BrucePay** [comment]
@Ayanmullick I'm not sure I understand. This module lets you load installed but incompatible v5 modules into v6. PowerShell get lets you download modules into a directory specific to the PowerShell version. I don't really see the connection...

**Comment by Ayanmullick** [comment]
Most windows PowerShell modules are working seamlessly on PowerShell 7.0.0-rc.2. Closing.
